# This file is covered by the LICENSE file in the root of this project.
labels:
  0: "noise"
  1: "animal"
  2: "human.pedestrian.adult"
  3: "human.pedestrian.child"
  4: "human.pedestrian.construction_worker"
  5: "human.pedestrian.personal_mobility"
  6: "human.pedestrian.police_officer"
  7: "human.pedestrian.stroller"
  8: "human.pedestrian.wheelchair"
  9: "movable_object.barrier"
  10: "movable_object.debris"
  11: "movable_object.pushable_pullable"
  12: "movable_object.trafficcone"
  13: "static_object.bicycle_rack"
  14: "vehicle.bicycle"
  15: "vehicle.bus.bendy"
  16: "vehicle.bus.rigid"
  17: "vehicle.car"
  18: "vehicle.construction"
  19: "vehicle.emergency.ambulance"
  20: "vehicle.emergency.police"
  21: "vehicle.motorcycle"
  22: "vehicle.trailer"
  23: "vehicle.truck"
  24: "flat.driveable_surface"
  25: "flat.other"
  26: "flat.sidewalk"
  27: "flat.terrain"
  28: "static.manmade"
  29: "static.other"
  30: "static.vegetation"
  31: "vehicle.ego"
  32: "unlabled"
  202: "human.pedestrian.adult.moving"
  203: "human.pedestrian.child.moving"
  204: "human.pedestrian.construction_worker.moving"
  205: "human.pedestrian.personal_mobility.moving"
  206: "human.pedestrian.police_officer.moving"
  207: "human.pedestrian.stroller.moving"
  208: "human.pedestrian.wheelchair.moving"
  214: "vehicle.bicycle.moving"
  215: "vehicle.bus.bendy.moving"
  216: "vehicle.bus.rigid.moving"
  217: "vehicle.car.moving"
  218: "vehicle.construction.moving"
  219: "vehicle.emergency.ambulance.moving"
  220: "vehicle.emergency.police.moving"
  221: "vehicle.motorcycle.moving"
  222: "vehicle.trailer.moving"
  223: "vehicle.truck.moving"
color_map: # bgr #original nuScenes colors below
  0: [0, 0, 0]
  1: [70, 130, 180]
  2: [0, 0, 230]
  3: [135, 206, 235]
  4: [100, 149, 237]
  5: [219, 112, 147]
  6: [0, 0, 128]
  7: [255, 30, 30]
  8: [240, 128, 128]
  9: [138, 43, 226]
  10: [112, 128, 144]
  11: [210, 105, 30]
  12: [105, 105, 105]
  13: [47, 79, 79]
  14: [188, 143, 143]
  15: [220, 20, 60]
  16: [255, 127, 80]
  17: [255, 69, 0]
  18: [255, 158, 0]
  19: [233, 150, 70]
  20: [255, 83, 0]
  21: [255, 215, 0]
  22: [255, 61, 99]
  23: [255, 140, 0]
  24: [255, 99, 71]
  25: [0, 207, 191]
  26: [175, 0, 75]
  27: [75, 0, 75]
  28: [112, 180, 60]
  29: [222, 184, 135]
  30: [255, 228, 196]
  31: [0, 175, 0]
  32: [200, 200, 200]
  202: [0, 0, 25]
  203: [0, 0, 25]
  204: [0, 0, 25]
  205: [0, 0, 25]
  206: [0, 0, 25]
  207: [0, 0, 25]
  208: [0, 0, 25]
  214: [0, 0, 255]
  215: [0, 0, 150]
  216: [0, 0, 150]
  217: [0, 0, 75]
  218: [0, 0, 255]
  219: [0, 0, 255]
  220: [0, 0, 255]
  221: [0, 0, 255]
  222: [0, 0, 255]
  223: [0, 0, 255]
content: # as a ratio with the total number of points
  0: 0.0017
  1: 0.0000
  2: 0.0006
  3: 0.0000
  4: 0.0001
  5: 0.0000
  6: 0.0000
  7: 0.0000
  8: 0.0000
  9: 0.0078
  10: 0.0001
  11: 0.0006
  12: 0.0006
  13: 0.0001
  14: 0.0001
  15: 0.0001
  16: 0.0017
  17: 0.0226
  18: 0.0012
  19: 0.0000
  20: 0.0000
  21: 0.0004
  22: 0.0030
  23: 0.0092
  24: 0.2673
  25: 0.0072
  26: 0.0592
  27: 0.0593
  28: 0.1503
  29: 0.0007
  30: 0.1034
  31: 0.2843
  32: 0.0000
  202: 0.0012
  203: 0.0000
  204: 0.0001
  205: 0.0000
  206: 0.0000
  207: 0.0000
  208: 0.0000
  214: 0.0000
  215: 0.0002
  216: 0.0018
  217: 0.0096
  218: 0.0001
  219: 0.0000
  220: 0.0000
  221: 0.0000
  222: 0.0012
  223: 0.0041
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
# Later in code: make 255 the 'unlabeled' label and shift all others down (-1) accordingly <-- 0=noise, rest+1
learning_map:
  0: 0 # noise
  1: 1 # animal
  2: 2 # human pedestrian adult
  3: 3 # human pedestrian child
  4: 4 # human pedestrian construction_worker
  5: 5 # human pedestrian personal_mobility
  6: 6 # human pedestrian police_officer
  7: 7 # human pedestrian stroller
  8: 8 # human pedestrian wheelchair
  9: 9 # movable_object barrier
  10: 10 # movable_object debris
  11: 11 # movable_object pushable_pullable
  12: 12 # movable_object trafficcone
  13: 13 # static_object.bicycle_rack
  14: 14 # vehicle bicycle
  15: 15 # vehicle bus bendy
  16: 16 # vehicle bus rigid
  17: 17 # vehicle car
  18: 18 # vehicle construction
  19: 19 # vehicle emergency ambulance
  20: 20 # vehicle emergency police
  21: 21 # vehicle motorcycle
  22: 22 # vehicle trailer
  23: 23 # vehicle truck
  24: 24 # flat driveable_surface
  25: 25 # flat other
  26: 26 # flat sidewalk
  27: 27 # flat terrain
  28: 28 # static manmade
  29: 29 # static other
  30: 30 # static vegetation
  31: 31 # vehicle ego
  32: 32 # unlabeled - only containing geometry
  202: 2 # moving mapped back to original - human pedestrian adult moving
  203: 3 # moving mapped back to original - human pedestrian child moving
  204: 4 # moving mapped back to original - human pedestrian construction_worker moving
  205: 5 # moving mapped back to original - human pedestrian personal_mobility moving
  206: 6 # moving mapped back to original - human pedestrian police_officer moving
  207: 8 # moving mapped back to original - human pedestrian stroller moving
  208: 8 # moving mapped back to original - human pedestrian wheelchair moving
  214: 14 # moving mapped back to original - vehicle bicycle moving
  215: 15 # moving mapped back to original - vehicle bus bendy moving
  216: 16 # moving mapped back to original - vehicle bus rigid moving
  217: 17 # moving mapped back to original - vehicle car moving
  218: 18 # moving mapped back to original - vehicle construction moving
  219: 19 # moving mapped back to original - vehicle emergency ambulance moving
  220: 20 # moving mapped back to original - vehicle emergency police moving
  221: 21 # moving mapped back to original - vehicle motorcycle moving
  222: 22 # moving mapped back to original - vehicle trailer moving
  223: 23 # moving mapped back to original - vehicle truck moving

learning_map_inv: # inverse of previous map
  0: 0 #noise
  1: 1 #animal
  2: 2 #static.object
  3: 3 #human.pedestrian.adult
  4: 4 #human.pedestrian.child
  5: 5 #human.pedestrian.construction_worker
  6: 6 #human.pedestrian.personal_mobility
  7: 7 #human.pedestrian.police_officer
  8: 8 #human.pedestrian.stroller
  9: 9 #human.pedestrian.wheelchair
  10: 10 #flat.driveable_surface
  11: 11 #flat.sidewalk
  12: 12 #flat.terrain
  13: 13 #flat.other
  14: 14 #vehicle.car
  15: 15 #vehicle.bus.bendy
  16: 16 #vehicle.bus.rigid
  17: 17 #vehicle.bicycle
  18: 18 #vehicle.motorcycle
  19: 19 #vehicle.truck
  20: 20 #vehicle.trailer
  21: 21 #vehicle.construction
  22: 22 #vehicle.emergency.ambulance
  23: 23 #vehicle.emergency.police
  24: 24 #static.vegetation
  25: 25 #static.manmade
  26: 26 #static_object.bicycle_rack
  27: 27 #movable_object.barrier
  28: 28 #movable_object.debris
  29: 29 #movable_object.trafficcone
  30: 30 #movable_object.pushable_pullable
  31: 31 #vehicle ego
  32: 32 #static.geometry (unlabled static frames)

learning_ignore: # Ignore classes
  0: True #noise
  1: False #animal
  2: False #static.object
  3: False #human.pedestrian.adult
  4: False #human.pedestrian.child
  5: False #human.pedestrian.construction_worker
  6: False #human.pedestrian.personal_mobility
  7: False #human.pedestrian.police_officer
  8: False #human.pedestrian.stroller
  9: False #human.pedestrian.wheelchair
  10: False #flat.driveable_surface
  11: False #flat.sidewalk
  12: False #flat.terrain
  13: False #flat.other
  14: False #vehicle.car
  15: False #vehicle.bus
  16: False #vehicle.bus
  17: False #vehicle.bicycle
  18: False #vehicle.motorcycle
  19: False #vehicle.truck
  20: False #vehicle.trailer
  21: False #vehicle.construction
  22: False #vehicle.emergency
  23: False #vehicle.emergency
  24: False #static.vegetation
  25: False #static.manmade
  26: False #static_object.bicycle_rack
  27: False #movable_object.barrier
  28: False #movable_object.debris
  29: False #movable_object.trafficcone
  30: False #movable_object.pushable_pullable
  31: False #static.geometry

#splits https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/splits.py
split: # sequence numbers
  train:
    - 0001
    - 0002
    - 0041
    - 0042
    - 0043
    - 0044
    - 0045
    - 0046
    - 0047
    - 0048
    - 0049
    - 0050
    - 0051
    - 0052
    - 0053
    - 0054
    - 0055
    - 0056
    - 0057
    - 0058
    - 0059
    - 0060
    - 0061
    - 0062
    - 0063
    - 0064
    - 0065
    - 0066
    - 0067
    - 0068
    - 0069
    - 0070
    - 0071
    - 0072
    - 0073
    - 0074
    - 0075
    - 0076
    - 0161
    - 0162
    - 0163
    - 0164
    - 0165
    - 0166
    - 0167
    - 0168
    - 0170
    - 0171
    - 0172
    - 0173
    - 0174
    - 0175
    - 0176
    - 0190
    - 0191
    - 0192
    - 0193
    - 0194
    - 0195
    - 0196
    - 0199
    - 0200
    - 0202
    - 0203
    - 0204
    - 0206
    - 0207
    - 0208
    - 0209
    - 0210
    - 0211
    - 0212
    - 0213
    - 0214
    - 0254
    - 0255
    - 0256
    - 0257
    - 0258
    - 0259
    - 0260
    - 0261
    - 0262
    - 0263
    - 0264
    - 0283
    - 0284
    - 0285
    - 0286
    - 0287
    - 0288
    - 0289
    - 0290
    - 0291
    - 0292
    - 0293
    - 0294
    - 0295
    - 0296
    - 0297
    - 0298
    - 0299
    - 0300
    - 0301
    - 0302
    - 0303
    - 0304
    - 0305
    - 0306
    - 0315
    - 0316
    - 0317
    - 0318
    - 0321
    - 0323
    - 0324
    - 0347
    - 0348
    - 0349
    - 0350
    - 0351
    - 0352
    - 0353
    - 0354
    - 0355
    - 0356
    - 0357
    - 0358
    - 0359
    - 0360
    - 0361
    - 0362
    - 0363
    - 0364
    - 0365
    - 0366
    - 0367
    - 0368
    - 0369
    - 0370
    - 0371
    - 0372
    - 0373
    - 0374
    - 0375
    - 0382
    - 0420
    - 0421
    - 0422
    - 0423
    - 0424
    - 0425
    - 0426
    - 0427
    - 0428
    - 0429
    - 0430
    - 0431
    - 0432
    - 0433
    - 0434
    - 0435
    - 0436
    - 0437
    - 0438
    - 0439
    - 0457
    - 0458
    - 0459
    - 0461
    - 0462
    - 0463
    - 0464
    - 0465
    - 0467
    - 0468
    - 0469
    - 0471
    - 0472
    - 0474
    - 0475
    - 0476
    - 0477
    - 0478
    - 0479
    - 0480
    - 0566
    - 0568
    - 0570
    - 0571
    - 0572
    - 0573
    - 0574
    - 0575
    - 0576
    - 0577
    - 0578
    - 0580
    - 0582
    - 0583
    - 0665
    - 0666
    - 0667
    - 0668
    - 0669
    - 0670
    - 0671
    - 0672
    - 0673
    - 0674
    - 0675
    - 0676
    - 0677
    - 0678
    - 0679
    - 0681
    - 0683
    - 0684
    - 0685
    - 0686
    - 0687
    - 0688
    - 0689
    - 0739
    - 0740
    - 0741
    - 0744
    - 0746
    - 0747
    - 0749
    - 0750
    - 0751
    - 0752
    - 0757
    - 0758
    - 0759
    - 0760
    - 0761
    - 0762
    - 0763
    - 0764
    - 0765
    - 0767
    - 0768
    - 0769
    - 0868
    - 0869
    - 0870
    - 0871
    - 0872
    - 0873
    - 0875
    - 0876
    - 0877
    - 0878
    - 0880
    - 0882
    - 0883
    - 0884
    - 0885
    - 0886
    - 0887
    - 0888
    - 0889
    - 0890
    - 0891
    - 0892
    - 0893
    - 0894
    - 0895
    - 0896
    - 0897
    - 0898
    - 0899
    - 0900
    - 0901
    - 0902
    - 0903
    - 0945
    - 0947
    - 0949
    - 0952
    - 0953
    - 0955
    - 0956
    - 0957
    - 0958
    - 0959
    - 0960
    - 0961
    - 0975
    - 0976
    - 0977
    - 0978
    - 0979
    - 0980
    - 0981
    - 0982
    - 0983
    - 0984
    - 0988
    - 0989
    - 0990
    - 0991
    - 1011
    - 1012
    - 1013
    - 1014
    - 1015
    - 1016
    - 1017
    - 1018
    - 1019
    - 1020
    - 1021
    - 1022
    - 1023
    - 1024
    - 1025
    - 1074
    - 1075
    - 1076
    - 1077
    - 1078
    - 1079
    - 1080
    - 1081
    - 1082
    - 1083
    - 1084
    - 1085
    - 1086
    - 1087
    - 1088
    - 1089
    - 1090
    - 1091
    - 1092
    - 1093
    - 1094
    - 1095
    - 1096
    - 1097
    - 1098
    - 1099
    - 1100
    - 1101
    - 1102
    - 1104
    - 1105
  valid:
    - 0003
    - 0012
    - 0013
    - 0014
    - 0015
    - 0016
    - 0017
    - 0018
    - 0035
    - 0036
    - 0038
    - 0039
    - 0092
    - 0093
    - 0094
    - 0095
    - 0096
    - 0097
    - 0098
    - 0099
    - 0100
    - 0101
    - 0102
    - 0103
    - 0104
    - 0105
    - 0106
    - 0107
    - 0108
    - 0109
    - 0110
    - 0221
    - 0268
    - 0269
    - 0270
    - 0271
    - 0272
    - 0273
    - 0274
    - 0275
    - 0276
    - 0277
    - 0278
    - 0329
    - 0330
    - 0331
    - 0332
    - 0344
    - 0345
    - 0346
    - 0519
    - 0520
    - 0521
    - 0522
    - 0523
    - 0524
    - 0552
    - 0553
    - 0554
    - 0555
    - 0556
    - 0557
    - 0558
    - 0559
    - 0560
    - 0561
    - 0562
    - 0563
    - 0564
    - 0565
    - 0625
    - 0626
    - 0627
    - 0629
    - 0630
    - 0632
    - 0633
    - 0634
    - 0635
    - 0636
    - 0637
    - 0638
    - 0770
    - 0771
    - 0775
    - 0777
    - 0778
    - 0780
    - 0781
    - 0782
    - 0783
    - 0784
    - 0794
    - 0795
    - 0796
    - 0797
    - 0798
    - 0799
    - 0800
    - 0802
    - 0904
    - 0905
    - 0906
    - 0907
    - 0908
    - 0909
    - 0910
    - 0911
    - 0912
    - 0913
    - 0914
    - 0915
    - 0916
    - 0917
    - 0919
    - 0920
    - 0921
    - 0922
    - 0923
    - 0924
    - 0925
    - 0926
    - 0927
    - 0928
    - 0929
    - 0930
    - 0931
    - 0962
    - 0963
    - 0966
    - 0967
    - 0968
    - 0969
    - 0971
    - 0972
    - 1059
    - 1060
    - 1061
    - 1062
    - 1063
    - 1064
    - 1065
    - 1066
    - 1067
    - 1068
    - 1069
    - 1070
    - 1071
    - 1072
    - 1073
  test: